create table CUENTA (
   IDCUENTA             int                  not null,
   SALDO                numeric(10,2)        null,
   constraint PK_CUENTA primary key (IDCUENTA)
);

ALTER TABLE CUENTA ADD CHECK (SALDO>=0);

create table MOVIMIENTO (
   IDMOVIMIENTO         int  GENERATED BY DEFAULT AS IDENTITY(START WITH 1 INCREMENT BY 1)   not null,
   IDCUENTA             int                  null,
   TIPOMOVIMIENTO       varchar(2)           null,
   VALOR                numeric(10,2)        null,
   constraint PK_MOVIMIENTO primary key (IDMOVIMIENTO)
);

create table TRANSFERENCIA (
   IDCUENTAORIGEN       int                  null,
   IDCUENTADESTINO      int                  null,
   IMPORTE              numeric(10,2)        null
);

alter table MOVIMIENTO
   add constraint FK_MOVIMIEN_FK3_CUENTA foreign key (IDCUENTA)
      references CUENTA (IDCUENTA);


alter table TRANSFERENCIA
   add constraint FK_cuentadestino_CUENTA foreign key (IDCUENTADESTINO)
      references CUENTA (IDCUENTA);

alter table TRANSFERENCIA
   add constraint FK_cuentaorigen_CUENTA foreign key (IDCUENTAORIGEN)
      references CUENTA (IDCUENTA);

--Inser para las cuentas--
INSERT INTO CUENTA VALUES(1,200),(2,0);

CREATE PROCEDURE PA_INSERTAR_TRANSACCIONAL
(PIDCUENTAORIGEN INT, PIDCUENTADESTINO INT,  PVALOR NUMERIC(10,2))
AS $$
BEGIN
BEGIN 
   insert into TRANSFERENCIA values(PIDCUENTAORIGEN,PIDCUENTADESTINO,PVALOR);
   insert into MOVIMIENTO(IDCUENTA,TIPOMOVIMIENTO,VALOR) values(PIDCUENTADESTINO,'A',PVALOR);
   update CUENTA set SALDO=saldo+PVALOR where IDCUENTA=PIDCUENTADESTINO;
   insert into MOVIMIENTO(IDCUENTA,TIPOMOVIMIENTO,VALOR) values(PIDCUENTAORIGEN,'D',PVALOR);
   update CUENTA set SALDO=saldo-PVALOR where IDCUENTA=PIDCUENTAORIGEN;
END;
EXCEPTION
WHEN OTHERS THEN 
ROLLBACK;
raise exception 'No se pudo ejecutar la transacción';
END;  $$ LANGUAGE plpgsql;



CREATE PROCEDURE PA_INSERTAR_NO_TRANSACCIONAL
(PIDCUENTAORIGEN INT, PIDCUENTADESTINO INT,  PVALOR NUMERIC(10,2))
AS $$
BEGIN
 insert into TRANSFERENCIA values(PIDCUENTAORIGEN,PIDCUENTADESTINO,PVALOR);
 insert into MOVIMIENTO(IDCUENTA,TIPOMOVIMIENTO,VALOR) values(PIDCUENTADESTINO,'A',PVALOR);
 update CUENTA set SALDO=saldo+PVALOR where IDCUENTA=PIDCUENTADESTINO;
 insert into MOVIMIENTO(IDCUENTA,TIPOMOVIMIENTO,VALOR) values(PIDCUENTAORIGEN,'D',PVALOR);
 update CUENTA set SALDO=saldo-PVALOR where IDCUENTA=PIDCUENTAORIGEN;
END;
$$ LANGUAGE plpgsql;